Support endpoints in nACL generation
np-guard/vpc-network-config-synthesis pull request #157
Opened 2024-06-30 13:35 UTC by YairSlobodin1

2024-07-11 11:09 UTC, kyorav reviewed
I tested a couple of scenarios, LGTM.

2024-07-15 08:56 UTC, zivnevo requested changes

2024-07-15 08:56 UTC, zivnevo commented on pkg/ir/unspecified.go
> +					break
I don't understand this break - don't we want all NIFs in this list?

2024-07-15 09:02 UTC, YairSlobodin1 commented on pkg/synth/acl.go
> +func updateEndpoint(s *ir.ConfigDefs, resource ir.Resource, addr *ipblock.IPBlock) *ipblock.IPBlock {
Should I change Src and Dst be `*Resource` [here](https://github.com/np-guard/vpc-network-config-synthesis/blob/main/pkg/ir/spec.go#L31)?

2024-07-15 11:00 UTC, YairSlobodin1 commented on pkg/synth/acl.go
> +		nifName, _ := s.NIFFromIP(addr)
we check this [before](https://github.com/np-guard/vpc-network-config-synthesis/blob/main/pkg/ir/spec.go#L297).

2024-07-15 11:25 UTC, zivnevo requested changes

2024-07-15 11:25 UTC, zivnevo commented on pkg/ir/unspecified.go
> +			subnetInSegment := false
Consider using [a labeled break statement](https://stackoverflow.com/questions/51996175/how-to-break-out-of-nested-loops-in-go) instead.
Another option is a labeled `continue` statement.

2024-07-15 11:25 UTC, zivnevo commented on pkg/synth/acl.go
> +		nifName, _ := s.NIFFromIP(addr)
got it. Maybe just add a comment

2024-07-15 11:51 UTC, zivnevo approved these changes

2024-07-16 06:50 UTC, merged