Optimize nACL generation
np-guard/vpc-network-config-synthesis pull request #164
Opened 2024-07-01 12:32 UTC by YairSlobodin1

2024-07-18 08:36 UTC, zivnevo requested changes

2024-07-18 08:36 UTC, zivnevo commented on pkg/synth/acl.go
Functions in this file have too many parameters. Spec and options are carried deep down the stack.
Consider a dedicated struct, and make all/some of the functions its methods. Something like
```golang
type ACLSynthesizer struct{
	spec *ir.Spec
	defs *ir.Definitions
	SingleACL bool
}
```

2024-07-18 08:36 UTC, zivnevo commented on pkg/synth/acl.go
> +				allowDirectedConnection(src, dst, srcCidrs, dstCidrs, internalSrc, internalDst, trackedProtocol.Protocol, reason, result, single)
The mapping of local variables to function parameters is confusing:
`src` -> `srcCidr`
`dst` -> `dstCidr`
`srcCidrs` -> `srcSubnets`
`dstCidrs` -> `dstSubnets`

2024-07-18 08:36 UTC, zivnevo commented on pkg/synth/acl.go
> +func allowDirectedConnection(srcCidr, dstCidr *ipblock.IPBlock, srcSubnets, dstSubnets []*ir.ConnResource, internalSrc, internalDst bool,
I suggest this function is split into two functions: `allowConnectionFronSrc` and `allowConnectionToDst`

2024-07-18 08:36 UTC, zivnevo commented on pkg/synth/acl.go
> +// external with its IPAddrs), to make it convenient to go through all pairs of subnets in allowDirectedConnection function.
Also explain what is the `addrs` parameter and why/when it is changed in the returned values.

2024-07-18 08:36 UTC, zivnevo commented on pkg/synth/acl.go
> +				addRuleToACL(result, ir.AllowReceive(*response), srcSubnet, internal, singleACL)
There is no point in taking the pointer of a struct and then only using it for dereferencing.
Better change `AllowReceive` and `AllowSend` (and `packetACLRule`) to take a pointer to `ir.Packet`.

2024-07-18 08:36 UTC, zivnevo commented on pkg/synth/acl.go
> +		result[i] = &connResource
```suggestion
		result[i] = &ir.ConnResource{Name: subnet, Addrs: s.Subnets[subnet].Address()}
```

2024-07-22 11:09 UTC, YairSlobodin1 commented on pkg/synth/acl.go
> +	return e == ir.ResourceTypeSubnet || e == ir.ResourceTypeCidr || e == ir.ResourceTypeNIF || e == ir.ResourceTypeExternal
`ResourceType` is determined by the endpoint type (e.g subnet segment is saved as a subnet)

2024-07-22 13:53 UTC, zivnevo requested changes

2024-07-22 13:53 UTC, zivnevo commented on cmd/subcmds/acl.go
>  			}
```golang
			collection :=  synth.MakeACL(spec, args.singleacl)
```

2024-07-22 13:53 UTC, zivnevo commented on pkg/ir/packet.go
>  	return &ACLRule
```suggestion
	return packetACLRule(&Packet{Src: cidr, Dst: ipblock.GetCidrAll(), Protocol: AnyProtocol{}, Explanation: explanation}, Outbound, Deny)
```

2024-07-22 13:53 UTC, zivnevo commented on pkg/ir/packet.go
>  	return &ACLRule
```suggestion
	return packetACLRule(&Packet{Src: ipblock.GetCidrAll(), Dst: cidr, Protocol: AnyProtocol{}, Explanation: explanation}, Inbound, Deny)
```

2024-07-22 14:44 UTC, zivnevo approved these changes

2024-07-22 14:44 UTC, zivnevo commented on pkg/synth/acl.go
> +// MakeACL translatea.Spec to a collection of ACLs
```suggestion
// MakeACL translates Spec to a collection of ACLs
```
OK to push this fix to the following PR

2024-07-22 15:12 UTC, merged