Support json ouput for single nACL
np-guard/vpc-network-config-synthesis pull request #168
Opened 2024-07-02 12:17 UTC by YairSlobodin1

2024-07-11 13:55 UTC, kyorav reviewed
manual test looks good

2024-07-24 13:37 UTC, zivnevo requested changes

2024-07-29 05:42 UTC, zivnevo requested changes

2024-07-29 05:42 UTC, zivnevo commented on pkg/io/confio/acl.go
> +		if !ok { // single acl
```suggestion
	var aclItem *configModel.NetworkACL

	for i, subnet := range model.SubnetList {
		vpcName := subnet.VPC.Name
		aclName := ScopingString(*vpcName, *subnet.Name)

		acl, ok := collection.ACLs[*vpcName][aclName]
		if !ok { // single acl
```
Variables are not being re-used between loop iterations. Declaring them outside of the loop may confuse the reader.

2024-07-29 05:42 UTC, zivnevo commented on pkg/io/confio/acl.go
> +
```suggestion
		vpcName := *subnet.VPC.Name
		aclName := ScopingString(vpcName, *subnet.Name)

```
Avoid dereferencing strings again and again (strings are just pointers anyway)

2024-07-29 06:57 UTC, zivnevo approved these changes

2024-07-29 06:58 UTC, merged