Optimization of SGs
np-guard/vpc-network-config-synthesis pull request #191
Opened 2024-08-26 09:12 UTC by YairSlobodin1

2024-09-30 13:18 UTC, zivnevo requested changes

2024-09-30 13:24 UTC, YairSlobodin1 commented on cmd/subcmds/optimizeSG.go
> +	if optimize.ReduceSGRules(sgs, args.sgName) != nil {
fixed in [#193](https://github.com/np-guard/vpc-network-config-synthesis/blob/output/cmd/subcmds/optimize.go#L32-L42)

2024-09-30 14:34 UTC, zivnevo commented on cmd/subcmds/root.go
> +	sgNameFlag     = "sg-name"
I would say yes.

2024-10-01 18:38 UTC, YairSlobodin1 commented on cmd/subcmds/root.go
> +	sgNameFlag     = "sg-name"
fixed in #193

2024-12-18 10:13 UTC, zivnevo requested changes

2024-12-18 10:13 UTC, zivnevo commented on README.md
> +a required connection between NIFs/VSIs/VPEs implies connectivity will be allowed between the subnets they are contained in.
```suggestion
A required connection between NIFs/VSIs/VPEs implies connectivity will be allowed between the subnets they are contained in.
```

2024-12-18 10:13 UTC, zivnevo commented on README.md
> +  -s, --spec string         JSON file containing spec file
```suggestion
Flags:
  -s, --spec string         JSON file containing spec file
```

2024-12-18 10:13 UTC, zivnevo commented on README.md
Add a run example for `vpcgen optimize sg` in the last section

2024-12-18 10:24 UTC, zivnevo approved these changes

2024-12-18 10:27 UTC, merged