Read sgs
np-guard/vpc-network-config-synthesis pull request #192
Opened 2024-08-26 09:42 UTC by YairSlobodin1

1st bullet

2024-09-30 13:01 UTC, zivnevo requested changes
Well structured code!
Just a few tiny things

2024-09-30 13:01 UTC, zivnevo commented on pkg/io/confio/parse_sgs.go
> +	isTCP := *rule.Protocol == "tcp"
```suggestion
	isTCP := *rule.Protocol == vpcv1.SecurityGroupRuleSecurityGroupRuleProtocolTcpudpProtocolTCPConst
```

2024-09-30 13:27 UTC, YairSlobodin1 commented on pkg/io/confio/parse_sgs.go
> +			continue
Im not sure what should I write in the warning

2024-09-30 13:52 UTC, zivnevo commented on pkg/io/confio/parse_sgs.go
> +			continue
missing SG/VPC name

2024-09-30 14:30 UTC, zivnevo approved these changes

2024-10-01 06:49 UTC, zivnevo approved these changes

2024-10-01 06:52 UTC, merged