nACL optimization - output
np-guard/vpc-network-config-synthesis pull request #233
Opened 2024-10-29 15:29 UTC by YairSlobodin1

3rd bullet of #227 

- [ ] csv & md
- [ ] tf
- [ ] json

2025-01-01 16:01 UTC, zivnevo requested changes

2025-01-02 08:02 UTC, YairSlobodin1 commented on test/main_test_list.go
added in #243

2025-01-02 08:37 UTC, zivnevo requested changes

2025-01-02 08:37 UTC, zivnevo commented on pkg/io/confio/acl.go
> +// o.w. it calls updateACL
fix comment

2025-01-02 08:37 UTC, zivnevo commented on pkg/io/confio/acl.go
> +// updateACL writes all the generates nACLs to the config object
fix comment

2025-01-02 09:10 UTC, zivnevo requested changes

2025-01-02 09:10 UTC, zivnevo commented on pkg/io/confio/acl.go
> +// updateACL writes  the generated nACL to the config object
fix comment

2025-01-02 09:21 UTC, zivnevo approved these changes

2025-01-02 09:27 UTC, merged