Optimize ACL
np-guard/vpc-network-config-synthesis pull request #243
Opened 2024-12-16 10:36 UTC by YairSlobodin1

2025-01-02 15:38 UTC, zivnevo requested changes

2025-01-02 15:38 UTC, zivnevo commented on pkg/optimize/acl/reduceCubes.go
> +		if p.S3.Equal(netset.NewAllTCPOnlySet()) || p.S3.Equal(netset.NewAllUDPOnlySet()) { // all tcp or udp ports
call `netset.NewAllTCPOnlySet()` and `netset.NewAllUDPOnlySet()` only once outside of the loop

2025-01-02 15:38 UTC, zivnevo commented on pkg/optimize/acl/reduceCubes.go
> +	allicmp := allICMP(aclCubes.icmpAllow)
rename to `allICMP`

2025-01-02 15:38 UTC, zivnevo commented on pkg/optimize/acl/cubesToRules.go
> +		if i > 0 && uncoveredHole(partitions[i].Left, partitions[i].Left) {
```suggestion
		if i > 0 && uncoveredHole(partitions[i-1].Left, partitions[i].Left) {
```

2025-01-02 15:38 UTC, zivnevo commented on pkg/optimize/acl/cubesToRules.go
> +	return touching
```suggestion
	return !touching
```

2025-01-02 15:38 UTC, zivnevo commented on pkg/optimize/acl/cubesToRules.go
> +func anyProtocolCubesToRules(cubes srcDstProduct, direction ir.Direction) []*ir.ACLRule {
needs dedicated tests

2025-01-02 15:38 UTC, zivnevo commented on pkg/optimize/acl/tcpudpCubesToRules.go
> +	isTCP := tcpudpTriples[0].S1.Elements()[0] == 0
```suggestion
	isTCP := tcpudpTriples[0].S1.Elements()[0] == netset.TCPCode
```

2025-01-02 15:42 UTC, YairSlobodin1 commented on pkg/optimize/acl/reduceCubes.go
> +func reduceACLCubes(aclCubes *aclCubesPerProtocol) {
the function already changed in #251 -- it creates also deny rules

2025-01-02 15:57 UTC, zivnevo requested changes

2025-01-02 15:57 UTC, zivnevo commented on test/expected/optimize_acl_md/nacl_expected.md
> + | testacl5-vpc--sub1-2 | sub1-2 | Outbound | 1 | Allow | 10.240.2.0/24, any port | 1.1.1.1, ports 1-20 | UDP | - |  |
not consistent with `details.txt`

2025-01-02 15:57 UTC, zivnevo commented on pkg/optimize/acl/reduceCubes.go
> +func reduceACLCubes(aclCubes *aclCubesPerProtocol) {
I still want this comment. You can change the comment in #251.

2025-01-02 16:28 UTC, YairSlobodin1 commented on test/expected/optimize_acl_md/nacl_expected.md
> + | testacl5-vpc--sub1-2 | sub1-2 | Outbound | 1 | Allow | 10.240.2.0/24, any port | 1.1.1.1, ports 1-20 | UDP | - |  |
why?

2025-01-03 08:38 UTC, zivnevo approved these changes

2025-01-05 10:39 UTC, merged